/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Asus
 */
public class LoginView extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(800, 500);
        this.repaint();
        //SetImageLabel(wallpaper, "src/images/wallpaper.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoPanel = new javax.swing.JPanel();
        wallpaper = new javax.swing.JLabel();
        HeaderPanel = new javax.swing.JPanel();
        CerrarPanel = new javax.swing.JPanel();
        lbCerrar = new javax.swing.JLabel();
        UserPanel = new javax.swing.JPanel();
        lbIniciarSesion = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbContra = new javax.swing.JLabel();
        fieldPass = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        subPass = new javax.swing.JLabel();
        subUser = new javax.swing.JLabel();
        BotonPanel = new javax.swing.JPanel();
        btnEnviar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoPanel.setBackground(new java.awt.Color(255, 255, 255));
        LogoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wallpaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paper.jpg"))); // NOI18N
        wallpaper.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        LogoPanel.add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 500));

        getContentPane().add(LogoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 500));

        HeaderPanel.setBackground(new java.awt.Color(153, 204, 255));
        HeaderPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderPanelMouseDragged(evt);
            }
        });
        HeaderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderPanelMousePressed(evt);
            }
        });

        CerrarPanel.setBackground(new java.awt.Color(153, 204, 255));

        lbCerrar.setBackground(new java.awt.Color(255, 255, 255));
        lbCerrar.setFont(lbCerrar.getFont().deriveFont(lbCerrar.getFont().getStyle() | java.awt.Font.BOLD, 30));
        lbCerrar.setForeground(new java.awt.Color(255, 0, 0));
        lbCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCerrar.setText("⮾");
        lbCerrar.setAlignmentY(2.0F);
        lbCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarVentana(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CerrarPanelLayout = new javax.swing.GroupLayout(CerrarPanel);
        CerrarPanel.setLayout(CerrarPanelLayout);
        CerrarPanelLayout.setHorizontalGroup(
            CerrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CerrarPanelLayout.createSequentialGroup()
                .addComponent(lbCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CerrarPanelLayout.setVerticalGroup(
            CerrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addGap(0, 762, Short.MAX_VALUE)
                .addComponent(CerrarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CerrarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(HeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        UserPanel.setBackground(new java.awt.Color(153, 204, 255));
        UserPanel.setFocusCycleRoot(true);
        UserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIniciarSesion.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lbIniciarSesion.setText("INICIAR SESIÓN");
        UserPanel.add(lbIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, 50));

        lbUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lbUsuario.setText("USUARIO");
        UserPanel.add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 88, 31));

        lbContra.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lbContra.setText("CONTRASEÑA");
        UserPanel.add(lbContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 129, -1));

        fieldPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fieldPass.setForeground(new java.awt.Color(204, 204, 204));
        fieldPass.setText("**********");
        fieldPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        fieldPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fieldPassMousePressed(evt);
            }
        });
        fieldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPassActionPerformed(evt);
            }
        });
        UserPanel.add(fieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 370, 30));

        txtUser.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(204, 204, 204));
        txtUser.setText("Ingrese nombre de usuario");
        txtUser.setToolTipText("");
        txtUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUserMousePressed(evt);
            }
        });
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        UserPanel.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 370, 30));

        subPass.setFont(new java.awt.Font("Agency FB", 1, 22)); // NOI18N
        subPass.setForeground(new java.awt.Color(51, 153, 255));
        subPass.setText("__________________________________________");
        UserPanel.add(subPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 400, 40));

        subUser.setFont(new java.awt.Font("Agency FB", 1, 22)); // NOI18N
        subUser.setForeground(new java.awt.Color(51, 153, 255));
        subUser.setText("__________________________________________");
        UserPanel.add(subUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 400, 40));

        BotonPanel.setBackground(new java.awt.Color(51, 153, 255));

        btnEnviar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEnviar.setText("Entrar");
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnviarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonPanelLayout = new javax.swing.GroupLayout(BotonPanel);
        BotonPanel.setLayout(BotonPanelLayout);
        BotonPanelLayout.setHorizontalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        BotonPanelLayout.setVerticalGroup(
            BotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        UserPanel.add(BotonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 120, 40));

        getContentPane().add(UserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 470, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void fieldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPassActionPerformed

    private void cerrarVentana(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarVentana
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cerrarVentana

    private void HeaderPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanelMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();

    }//GEN-LAST:event_HeaderPanelMousePressed

    private void HeaderPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderPanelMouseDragged

    private void lbCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCerrarMouseEntered
        // TODO add your handling code here:
        CerrarPanel.setBackground(Color.red);
        lbCerrar.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbCerrarMouseEntered

    private void lbCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCerrarMouseExited
        // TODO add your handling code here:
        Color base = new Color(153, 204, 255);
        CerrarPanel.setBackground(base);
        lbCerrar.setForeground(Color.RED);
    }//GEN-LAST:event_lbCerrarMouseExited

    private void btnEnviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseEntered
        // TODO add your handling code here:
        btnEnviar.setForeground(Color.BLACK);
        BotonPanel.setBackground(new Color(218, 233, 249));
    }//GEN-LAST:event_btnEnviarMouseEntered

    private void btnEnviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseExited
        // TODO add your handling code here:[51,153,255]
        btnEnviar.setForeground(Color.WHITE);
        BotonPanel.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_btnEnviarMouseExited

    private void txtUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMousePressed
        // TODO add your handling code here:
        if (txtUser.getText().equals("Ingrese nombre de usuario")) {
            txtUser.setText("");
            txtUser.setForeground(Color.BLACK);
        }
        if (String.valueOf(fieldPass.getPassword()).isEmpty()) {
            fieldPass.setText("**********");
            fieldPass.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtUserMousePressed

    private void fieldPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldPassMousePressed
        // TODO add your handling code here:
        if (txtUser.getText().isEmpty()) {
            txtUser.setText("Ingrese nombre de usuario");
            txtUser.setForeground(Color.GRAY);
        }
        if (String.valueOf(fieldPass.getPassword()).equals("**********")) {
            fieldPass.setText("");
            fieldPass.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_fieldPassMousePressed

    

    private void SetImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonPanel;
    private javax.swing.JPanel CerrarPanel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JLabel btnEnviar;
    private javax.swing.JPasswordField fieldPass;
    private javax.swing.JLabel lbCerrar;
    private javax.swing.JLabel lbContra;
    private javax.swing.JLabel lbIniciarSesion;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel subPass;
    private javax.swing.JLabel subUser;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
