/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.SettingsController;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Asus
 */
public class SystemView extends javax.swing.JFrame {

    /**
     * Creates new form SystemView
     */
    public SystemView() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(1208, 680);
        setResizable(false);
        setTitle("Dashboard");
        SettingsController setting = new SettingsController(this);
        jTableProductos.getTableHeader().setDefaultRenderer(new HeaderColor());
        jTableProductos.setRowHeight(25);
        this.repaint();
    }

    public class HeaderColor extends DefaultTableCellRenderer {

        public HeaderColor() {
            setOpaque(true);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);
            setForeground(Color.WHITE);
            setFont(new Font("Roboto Black",Font.PLAIN,14));
            setBackground(new Color(72, 144, 215));
                //you can change the color that u want 
            return this;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        jPanelProducts = new javax.swing.JPanel();
        jLabelProducts = new javax.swing.JLabel();
        jPanelPurchase = new javax.swing.JPanel();
        jLabelPurchase = new javax.swing.JLabel();
        jPanelCustomers = new javax.swing.JPanel();
        jLabelCustomers = new javax.swing.JLabel();
        jPanelEmployes = new javax.swing.JPanel();
        jLabelEmployes = new javax.swing.JLabel();
        jPanelSuppliers = new javax.swing.JPanel();
        jLabelSuppliers = new javax.swing.JLabel();
        jPanelCategories = new javax.swing.JPanel();
        jLabelCategories = new javax.swing.JLabel();
        jPanelReports = new javax.swing.JPanel();
        jLabelReports = new javax.swing.JLabel();
        jPanelSettings = new javax.swing.JPanel();
        jLabelSettings = new javax.swing.JLabel();
        UserPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelNombreUser = new javax.swing.JLabel();
        HeaderPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jTabbedContenido = new javax.swing.JTabbedPane();
        tabProductos = new javax.swing.JPanel();
        jPanelCrudProducto = new javax.swing.JPanel();
        jPanelHeaderProducto = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabelDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabelCategoria = new javax.swing.JLabel();
        jComboCategoria = new javax.swing.JComboBox<>();
        jLabelId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JPanel();
        labelBtnCancelar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        labelBtnEliminar = new javax.swing.JLabel();
        btnModificar = new javax.swing.JPanel();
        labelBtnModificar = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JPanel();
        labelBtnRegistrar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        tabCompras = new javax.swing.JPanel();
        tabClientes = new javax.swing.JPanel();
        tabEmpleados = new javax.swing.JPanel();
        tabProveedores = new javax.swing.JPanel();
        tabCategorias = new javax.swing.JPanel();
        tabReportes = new javax.swing.JPanel();
        tabConfiguracion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPanel.setBackground(new java.awt.Color(104, 163, 222));
        MenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelProducts.setBackground(new java.awt.Color(104, 163, 222));
        jPanelProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelProducts.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabelProducts.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/box.png"))); // NOI18N
        jLabelProducts.setText("  Productos");

        javax.swing.GroupLayout jPanelProductsLayout = new javax.swing.GroupLayout(jPanelProducts);
        jPanelProducts.setLayout(jPanelProductsLayout);
        jPanelProductsLayout.setHorizontalGroup(
            jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductsLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabelProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelProductsLayout.setVerticalGroup(
            jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        MenuPanel.add(jPanelProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 35));

        jPanelPurchase.setBackground(new java.awt.Color(104, 163, 222));
        jPanelPurchase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelPurchase.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabelPurchase.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPurchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/purchase.png"))); // NOI18N
        jLabelPurchase.setText("  Compras");

        javax.swing.GroupLayout jPanelPurchaseLayout = new javax.swing.GroupLayout(jPanelPurchase);
        jPanelPurchase.setLayout(jPanelPurchaseLayout);
        jPanelPurchaseLayout.setHorizontalGroup(
            jPanelPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPurchaseLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabelPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelPurchaseLayout.setVerticalGroup(
            jPanelPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPurchase, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        MenuPanel.add(jPanelPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 35));

        jPanelCustomers.setBackground(new java.awt.Color(104, 163, 222));
        jPanelCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelCustomers.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabelCustomers.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer.png"))); // NOI18N
        jLabelCustomers.setText("  Clientes");

        javax.swing.GroupLayout jPanelCustomersLayout = new javax.swing.GroupLayout(jPanelCustomers);
        jPanelCustomers.setLayout(jPanelCustomersLayout);
        jPanelCustomersLayout.setHorizontalGroup(
            jPanelCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustomersLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabelCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCustomersLayout.setVerticalGroup(
            jPanelCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustomersLayout.createSequentialGroup()
                .addComponent(jLabelCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuPanel.add(jPanelCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 35));

        jPanelEmployes.setBackground(new java.awt.Color(104, 163, 222));
        jPanelEmployes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelEmployes.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabelEmployes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmployes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employee.png"))); // NOI18N
        jLabelEmployes.setText("  Empleados");

        javax.swing.GroupLayout jPanelEmployesLayout = new javax.swing.GroupLayout(jPanelEmployes);
        jPanelEmployes.setLayout(jPanelEmployesLayout);
        jPanelEmployesLayout.setHorizontalGroup(
            jPanelEmployesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmployesLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabelEmployes, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelEmployesLayout.setVerticalGroup(
            jPanelEmployesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmployesLayout.createSequentialGroup()
                .addComponent(jLabelEmployes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuPanel.add(jPanelEmployes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 200, 35));

        jPanelSuppliers.setBackground(new java.awt.Color(104, 163, 222));
        jPanelSuppliers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelSuppliers.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabelSuppliers.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSuppliers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/supplier.png"))); // NOI18N
        jLabelSuppliers.setText("  Proveedores");

        javax.swing.GroupLayout jPanelSuppliersLayout = new javax.swing.GroupLayout(jPanelSuppliers);
        jPanelSuppliers.setLayout(jPanelSuppliersLayout);
        jPanelSuppliersLayout.setHorizontalGroup(
            jPanelSuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuppliersLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabelSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelSuppliersLayout.setVerticalGroup(
            jPanelSuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuppliersLayout.createSequentialGroup()
                .addComponent(jLabelSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuPanel.add(jPanelSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 35));

        jPanelCategories.setBackground(new java.awt.Color(104, 163, 222));
        jPanelCategories.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelCategories.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabelCategories.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCategories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/categories.png"))); // NOI18N
        jLabelCategories.setText("  Categorias");

        javax.swing.GroupLayout jPanelCategoriesLayout = new javax.swing.GroupLayout(jPanelCategories);
        jPanelCategories.setLayout(jPanelCategoriesLayout);
        jPanelCategoriesLayout.setHorizontalGroup(
            jPanelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCategoriesLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabelCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCategoriesLayout.setVerticalGroup(
            jPanelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoriesLayout.createSequentialGroup()
                .addComponent(jLabelCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuPanel.add(jPanelCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 200, 35));

        jPanelReports.setBackground(new java.awt.Color(104, 163, 222));
        jPanelReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelReports.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabelReports.setForeground(new java.awt.Color(255, 255, 255));
        jLabelReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/business-report.png"))); // NOI18N
        jLabelReports.setText("  Reportes");

        javax.swing.GroupLayout jPanelReportsLayout = new javax.swing.GroupLayout(jPanelReports);
        jPanelReports.setLayout(jPanelReportsLayout);
        jPanelReportsLayout.setHorizontalGroup(
            jPanelReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReportsLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabelReports, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelReportsLayout.setVerticalGroup(
            jPanelReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReportsLayout.createSequentialGroup()
                .addComponent(jLabelReports, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuPanel.add(jPanelReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 200, 35));

        jPanelSettings.setBackground(new java.awt.Color(104, 163, 222));
        jPanelSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelSettings.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabelSettings.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        jLabelSettings.setText("  Configuraciones");

        javax.swing.GroupLayout jPanelSettingsLayout = new javax.swing.GroupLayout(jPanelSettings);
        jPanelSettings.setLayout(jPanelSettingsLayout);
        jPanelSettingsLayout.setHorizontalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSettingsLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelSettingsLayout.setVerticalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSettingsLayout.createSequentialGroup()
                .addComponent(jLabelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuPanel.add(jPanelSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 200, 35));

        getContentPane().add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 530));

        UserPanel.setBackground(new java.awt.Color(255, 255, 255));
        UserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N
        UserPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, 90));

        jLabel2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 51));
        jLabel2.setText(".");
        UserPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 30, -1));

        labelNombreUser.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        labelNombreUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreUser.setText("RaisaPham");
        UserPanel.add(labelNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, 30));

        getContentPane().add(UserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 150));

        HeaderPanel.setBackground(new java.awt.Color(104, 163, 222));
        HeaderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("     FARMACIA VIDA NATURAL");
        HeaderPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 500, 100));

        btnLogout.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnLogout.setText("Salir");
        HeaderPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 80, 30));

        getContentPane().add(HeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1010, 100));

        tabProductos.setBackground(new java.awt.Color(178, 210, 242));
        tabProductos.setFocusable(false);
        tabProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCrudProducto.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCrudProducto.setToolTipText("");
        jPanelCrudProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHeaderProducto.setBackground(new java.awt.Color(72, 144, 215));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRODUCTOS");

        javax.swing.GroupLayout jPanelHeaderProductoLayout = new javax.swing.GroupLayout(jPanelHeaderProducto);
        jPanelHeaderProducto.setLayout(jPanelHeaderProductoLayout);
        jPanelHeaderProductoLayout.setHorizontalGroup(
            jPanelHeaderProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderProductoLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderProductoLayout.setVerticalGroup(
            jPanelHeaderProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelCrudProducto.add(jPanelHeaderProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 30));

        jLabelPrecio.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelPrecio.setText("Precio de venta");
        jPanelCrudProducto.add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtPrecio.setBackground(new java.awt.Color(237, 242, 247));
        txtPrecio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtPrecio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        jPanelCrudProducto.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 220, 30));

        jLabelDescripcion.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelDescripcion.setText("Descripción");
        jPanelCrudProducto.add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        txtDescripcion.setBackground(new java.awt.Color(237, 242, 247));
        txtDescripcion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtDescripcion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        jPanelCrudProducto.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 220, 30));

        jLabelNombre.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelNombre.setText("Nombre");
        jPanelCrudProducto.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtNombre.setBackground(new java.awt.Color(237, 242, 247));
        txtNombre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        jPanelCrudProducto.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 220, 30));

        jLabelCodigo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelCodigo.setText("Código");
        jPanelCrudProducto.add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtCodigo.setBackground(new java.awt.Color(237, 242, 247));
        txtCodigo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        jPanelCrudProducto.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, 30));

        jLabelCategoria.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelCategoria.setText("Categoria");
        jPanelCrudProducto.add(jLabelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        jComboCategoria.setBackground(new java.awt.Color(237, 242, 247));
        jComboCategoria.setBorder(null);
        jPanelCrudProducto.add(jComboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 220, 30));

        jLabelId.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelId.setText("ID");
        jPanelCrudProducto.add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(221, 228, 236));
        txtId.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtId.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        txtId.setEnabled(false);
        txtId.setFocusable(false);
        jPanelCrudProducto.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 220, 30));

        btnCancelar.setBackground(new java.awt.Color(82, 109, 135));

        labelBtnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        labelBtnCancelar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        labelBtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        labelBtnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBtnCancelar.setText("CANCELAR");
        labelBtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnCancelarLayout.setVerticalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelCrudProducto.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 110, 40));

        btnEliminar.setBackground(new java.awt.Color(32, 81, 128));

        labelBtnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        labelBtnEliminar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        labelBtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        labelBtnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBtnEliminar.setText("ELIMINAR");
        labelBtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBtnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelCrudProducto.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 110, 40));

        btnModificar.setBackground(new java.awt.Color(121, 186, 249));

        labelBtnModificar.setBackground(new java.awt.Color(255, 255, 255));
        labelBtnModificar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        labelBtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        labelBtnModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBtnModificar.setText("MODIFICAR");
        labelBtnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnModificarLayout = new javax.swing.GroupLayout(btnModificar);
        btnModificar.setLayout(btnModificarLayout);
        btnModificarLayout.setHorizontalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnModificarLayout.setVerticalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelCrudProducto.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 110, 40));

        btnRegistrar.setBackground(new java.awt.Color(72, 144, 215));

        labelBtnRegistrar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        labelBtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        labelBtnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBtnRegistrar.setText("REGISTRAR");
        labelBtnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnRegistrarLayout = new javax.swing.GroupLayout(btnRegistrar);
        btnRegistrar.setLayout(btnRegistrarLayout);
        btnRegistrarLayout.setHorizontalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBtnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnRegistrarLayout.setVerticalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBtnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelCrudProducto.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 110, 40));

        tabProductos.add(jPanelCrudProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 20, 920, 270));

        jPanel1.setBackground(new java.awt.Color(72, 144, 215));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buscar");

        txtBuscarProducto.setBackground(new java.awt.Color(237, 242, 247));
        txtBuscarProducto.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtBuscarProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabProductos.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 300, 920, 40));

        jTableProductos.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Código", "Nombre", "Descripción", "Precio Venta", "Cantidad", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductos.setGridColor(new java.awt.Color(255, 255, 255));
        jTableProductos.setIntercellSpacing(new java.awt.Dimension(1, 1));
        jTableProductos.setOpaque(false);
        jTableProductos.setRowHeight(25);
        jTableProductos.setSelectionBackground(new java.awt.Color(123, 183, 243));
        jTableProductos.setShowHorizontalLines(true);
        jTableProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableProductos);
        if (jTableProductos.getColumnModel().getColumnCount() > 0) {
            jTableProductos.getColumnModel().getColumn(0).setResizable(false);
            jTableProductos.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableProductos.getColumnModel().getColumn(1).setResizable(false);
            jTableProductos.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTableProductos.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableProductos.getColumnModel().getColumn(4).setResizable(false);
            jTableProductos.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTableProductos.getColumnModel().getColumn(5).setResizable(false);
            jTableProductos.getColumnModel().getColumn(5).setPreferredWidth(20);
            jTableProductos.getColumnModel().getColumn(6).setResizable(false);
        }

        tabProductos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 350, 920, 190));

        jTabbedContenido.addTab("tab1", tabProductos);

        tabCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedContenido.addTab("tab2", tabCompras);

        tabClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedContenido.addTab("tab3", tabClientes);

        tabEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedContenido.addTab("tab4", tabEmpleados);

        tabProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedContenido.addTab("tab5", tabProveedores);

        tabCategorias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedContenido.addTab("tab6", tabCategorias);

        tabReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedContenido.addTab("tab7", tabReportes);

        tabConfiguracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedContenido.addTab("tab8", tabConfiguracion);

        getContentPane().add(jTabbedContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 1010, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel btnModificar;
    private javax.swing.JPanel btnRegistrar;
    private javax.swing.JButton jButton1;
    public javax.swing.JComboBox<Object> jComboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCategoria;
    public javax.swing.JLabel jLabelCategories;
    private javax.swing.JLabel jLabelCodigo;
    public javax.swing.JLabel jLabelCustomers;
    private javax.swing.JLabel jLabelDescripcion;
    public javax.swing.JLabel jLabelEmployes;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    public javax.swing.JLabel jLabelProducts;
    public javax.swing.JLabel jLabelPurchase;
    public javax.swing.JLabel jLabelReports;
    public javax.swing.JLabel jLabelSettings;
    public javax.swing.JLabel jLabelSuppliers;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanelCategories;
    private javax.swing.JPanel jPanelCrudProducto;
    public javax.swing.JPanel jPanelCustomers;
    public javax.swing.JPanel jPanelEmployes;
    private javax.swing.JPanel jPanelHeaderProducto;
    public javax.swing.JPanel jPanelProducts;
    public javax.swing.JPanel jPanelPurchase;
    public javax.swing.JPanel jPanelReports;
    public javax.swing.JPanel jPanelSettings;
    public javax.swing.JPanel jPanelSuppliers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedContenido;
    public javax.swing.JTable jTableProductos;
    public javax.swing.JLabel labelBtnCancelar;
    public javax.swing.JLabel labelBtnEliminar;
    public javax.swing.JLabel labelBtnModificar;
    public javax.swing.JLabel labelBtnRegistrar;
    private javax.swing.JLabel labelNombreUser;
    private javax.swing.JPanel tabCategorias;
    private javax.swing.JPanel tabClientes;
    private javax.swing.JPanel tabCompras;
    private javax.swing.JPanel tabConfiguracion;
    private javax.swing.JPanel tabEmpleados;
    private javax.swing.JPanel tabProductos;
    private javax.swing.JPanel tabProveedores;
    private javax.swing.JPanel tabReportes;
    public javax.swing.JTextField txtBuscarProducto;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
